version: '3'

services:

  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - "80:80"

  php:
    build: images/php
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: url_db
      DB_USERNAME: urluser
      DB_PASSWORD: urlpass

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jfioj23834iu1ijid
      MYSQL_DATABASE: url_db
      MYSQL_USER: urluser
      MYSQL_PASSWORD: urlpass
